version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.12

jobs:
  build:
    working_directory: ~/k8s-api-client
    machine: true
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:  
          name: Install Node.js
          command: |
            bash .circleci/load-nvm.sh

            nvm install v10.15.0
            nvm alias default v10.15.0

            # Install Yarn package manager
            sudo npm install --global yarn
    
      - run: 
          name: yarn install && yarn build
          command: |
            bash .circleci/load-nvm.sh

            yarn install
            yarn build

      # persist build
      - persist_to_workspace:
          root: ~/repo
          paths: .

      - run: 
          name: run tests and generate coverage report
          command: |
            bash .circleci/load-nvm.sh

            yarn docker:test
            
            # generate coverage report
            ./node_modules/.bin/nyc report --reporter=text-lcov > ./coverage.lcov
      
      # send test coverage
      - run: bash <(curl -s https://codecov.io/bash) -f ./coverage.lcov

      # test for outdated packages
      #- run: yarn outdated

      # lint code
      #- run: yarn lint

      # store artifacts
      - store_artifacts:
          path: ./coverage

      # store artifacts
      - store_artifacts:
          path: ./mochawesome-report

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - run:
          name: Publish package
          command: npm publish --access public


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: 
                - master

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/